import random

from selenium.webdriver.common.by import By

from selenium_ui.base_page import BasePage
from selenium_ui.conftest import print_timing
from selenium_ui.confluence.pages.pages import Login, AllUpdates
from util.conf import CONFLUENCE_SETTINGS

SPACE_KEYS = ["APATD", "ASLC", "ATA", "ABE", "AOSTD", "ASW", "AAPC", "ARECP", "AWHEP", "ANA", "AEWBB", "ACTE", "AVPS",
              "AALC", "ACSC", "ABWES", "ASPG", "ADFS", "ANSC", "ARJ", "AKLRK", "ASCNE", "ASE", "ACPB", "AATT", "AOPB",
              "ASCV", "AUOT", "AWMT", "AGPW", "ABRAS", "AMSVP", "AECR", "ATR", "AFA", "AAW", "AEPCF", "APVR", "APC",
              "ARPC", "AAR", "AUW", "API", "AIB", "APEUA", "AEC", "ATLCD", "AWT", "AGM", "ATD", "ASEMF", "ACMP", "ACSO",
              "AFIM", "ASSJD", "ARM", "AUCTS", "AVDHA", "AAALT", "ALI", "APBPF", "ACWCH", "ACL", "ADSTS", "ADSAE",
              "ASTC", "ABR", "ADDM", "AMPPA", "ANP", "ALA", "ARIR", "APBMR", "AOPA", "ASBS", "ACBSC", "ACF", "AEOO",
              "AUK", "ACN", "ATB", "ASMAI", "ACNT", "AMN", "AMZ", "AIDR", "AART", "ACS", "AIC", "ASTIB", "AEP", "ASPTO",
              "ADS", "ARA", "AASRI", "APTC", "AMP", "ADRP", "ACSOI", "ACLE", "AHR", "AHDA", "APA", "AMYR", "AKSPP",
              "AKQ", "ALEGC", "ACFED", "APFM", "ASC", "ACCRC", "AMVL", "ADBCE", "AKPED", "AABL", "ACRRC", "ACREW",
              "AFNAM", "AKHCE", "ASA", "AGH", "ACPR", "AMQ", "AWCDH", "AED", "ABIV", "ASPDI", "ACAA", "AAHIB", "AEBH",
              "ACC", "AELEW", "APRM", "AMC", "ASSOS", "ACICE", "ADSEA", "AICEH", "ACPC", "AJS", "AEH", "ATIMM", "ACEGW",
              "ASRBH", "AIR", "APL", "ARED", "APDRB", "AODMM", "AMHH", "AESBC", "ASWOR", "ADWIS", "AOMR", "APAUF",
              "ACAD", "ADE", "ARET", "ARBAR", "APAB", "ACRAM", "ANMAF", "AWCE", "AMPOL", "ADLG", "AATEN", "ACBBI",
              "AFFE", "ATRMC", "AETHE", "AIA", "APDR", "ACI", "ALCC", "ASHCQ", "ABT", "AHHBP", "ALRS", "AMH", "ARVI",
              "ACFWA", "AVPR", "ALCAR", "ASWH", "ATEM", "ARPFD", "AHPH", "AHC", "ATSP", "AXMAE", "ACA", "AFCSC",
              "AAARE", "ACVMA", "ASP", "ASSC", "ALS", "AMMAB", "ABMES", "AFNIE", "AUMMM", "ATAC", "ACMEM", "APE",
              "ASPA", "AMMTW", "ADWL", "ATP", "AWB", "ALR", "ADHE", "ACST", "AADC", "ACQS", "AFAF", "AGDCT", "ABRC",
              "ABSA", "AEA", "AMMHP", "AMG", "ATMEC", "AWDLP", "AWMS", "AAI", "ATS", "ABTA", "AACAC", "AFPIP", "AEV",
              "ARVO", "AGP", "APT", "ASQJ", "AWMP", "APBH", "AMA", "ABEUC", "ARWBA", "ABKAP", "AMYD", "AAPCJ", "ANOFV",
              "ABFR", "ALAIM", "ATN", "ASNL", "ALO", "ARFBF", "ASD", "ATM", "APSF", "AEB", "AEUSV", "AFCP", "AVLMB",
              "AWSS", "AIEB", "ACBM", "ADB", "AIT", "ACSOC", "APCYU", "AAS", "ACDEK", "ABC", "ALRVA", "ACTEY", "AFF",
              "AMS", "ACTVE", "AIAOI", "APCC", "ACU", "ABWD", "AER", "AMRE", "ARLVN", "ARCEP", "ASF", "AAHBL", "AHL",
              "ARPMA", "AIPIU", "ATSRR", "ABA", "AGLRQ", "AMES", "AACF", "AAEP", "AAOA", "ADEO", "AWVTP", "AADYM",
              "ABFFT", "ADP", "AATA", "ASSB", "APRDO", "AWSH", "AEPBM", "ASBSP", "ACSSE", "ABKPT", "ASRGC", "ATV",
              "AAC", "AMDT", "AFW", "ABTRY", "AECST", "ACH", "AAFL", "AFH", "ASL", "ACUUM", "ARD", "AFAP", "APG",
              "ATPW", "AQGRM", "ARDCO", "ASDH", "ACAMI", "ACCPT", "ACTEP", "ANSW", "AHM", "ASB", "ASIS", "AAAC", "AGT",
              "ATSS", "ABTCN", "ACCTP", "AVMF", "ADAB", "ATSB", "ALDGL", "AFFA", "AKRT", "AMHPB", "ABS", "AAJUI",
              "AWSGT", "AMCBC", "AARP", "ANMGC", "AAT", "ARP", "AFD", "ASSL", "AVOEC", "ADPA", "ADL", "AFET", "AMMD",
              "AIAR", "ACTED", "AIRCA", "AWGPM", "AEG", "AVW", "AWBPP", "ACCF", "ALDBG", "AMGRR", "APGA", "ACDC",
              "AEAEP", "AAF", "AFRS", "ARPRC", "ASU", "ASHDP", "ATDT", "ACMN", "AMSPS", "APTVO", "ARSE", "AADQS", "ALT",
              "ACP", "AWW", "ANIZC", "ABHD", "ARSCH", "BSRW", "BCSE", "BCB", "BRSSK", "BAMW", "BSSBA", "BPDWP", "BSDSI",
              "BBBMP", "BOC", "BCSFI", "BHSI", "BGH", "BFEF", "BPD", "BRI", "BHR", "BSI", "BMPSR", "BVWMC", "BAF",
              "BSCP", "BMHP", "BUW", "BFLA", "BLPDC", "BCCO", "BSIIE", "BGVG", "BIART", "BSCEA", "BCM", "BKWBN", "BSBS",
              "BVJAO", "BCBA", "BMCA", "BMWSS", "BHEC", "BIOM", "BFA", "BDCG", "BFP", "BMC", "BTIA", "BDC", "BSM",
              "BBREA", "BPEH", "BVEAT", "BGAN", "BOH", "BNMCS", "BGP", "BRCL", "BSR", "BMKMW", "BIOP", "BCOS", "BDRI",
              "BTL", "BPCBV", "BRPT", "BFEC", "BMAPA", "BHS", "BFD", "BICM", "BPBCA", "BDIS", "BZW", "BKBSM", "BBPR",
              "BAL", "BHF", "BLAT", "BTLS", "BADRR", "BATLC", "BES", "BHXP", "BPA", "BACKA", "BRHFG", "BHIC", "BLBDR",
              "BYRT", "BGTBO", "BVGD", "BHMR", "BACSP", "BSFW", "BCW", "BIB", "BSAI", "BEOH", "BNCB", "BDRDB", "BVTB",
              "BHPSP", "BMS", "BCPE", "BRS", "BTSZC", "BRPAR", "BTWUS", "BTLBT", "BMTP", "BMMC", "BRRDM", "BRNFD",
              "BTPM", "BDFSF", "BCET", "BKS", "BSGI", "BODT", "BDP", "BEJ", "BPU", "BSTCD", "BNIS", "BSSN", "BASDE",
              "BATT", "BFES", "BSGLC", "BLSPC", "BRINM", "BKL", "BATWS", "BCR", "BSCOH", "BBQRA", "BWI", "BCA", "BTR",
              "BPAHN", "BPCI", "BCCNS", "BCLDD", "BITN", "BTLBJ", "BINTL", "BRTP", "BLF", "BCELC", "BKG", "BISRE",
              "BANI", "BMI", "BPSS", "BSFEG", "BSV", "BTSE", "BCCTB", "BSSRM", "BNSS", "BSRRC", "BIMF", "BPSE", "BDET",
              "BCCI", "BPJI", "BANS", "BTE", "BVSO", "BGPBP", "BMBIU", "BPTD", "BDLPC", "BFJ", "BEST", "BAMH", "BTVF",
              "BIPT", "BSP", "BIRMM", "BNACC", "BNDP", "BSBIA", "BIPBD", "BWF", "BRR", "BGBA", "BSE", "BPPEP", "BTRY",
              "BRMB", "BLCPE", "BNDDN", "BCBS", "BMM", "BSMUT", "BWKA", "BECWE", "BRC", "BCBL", "BAADS", "BRCP", "BEPS",
              "BISHP", "BOCDC", "BWARD", "BTSS", "BDF", "BTJA", "BSEEB", "BEC", "BIR", "BEBRT", "BPT", "BPLCC", "BAHA",
              "BCPAB", "BBVBA", "BOBB", "BUPDI", "BAA", "BSMF", "BBSC", "BBSMP", "BASAP", "BAP", "BBSA", "BREP",
              "BDCLW", "BMPM", "BSAE", "BACAE", "BFQTG", "BAASE", "BASSR", "BADG", "BOF", "BHEVD", "BTB", "BMEAM",
              "BDA", "BODFT", "BGSWV", "BABCA", "BPW", "BEW", "BSWE", "BTPF", "BMTCP", "BNS", "BBS", "BHMC", "BIP",
              "BLTCL", "BPS", "BRGDG", "BUST", "BPHY", "BPDC", "BCCW", "BTP", "BFC", "BSS", "BLSC", "BEM", "BAAC",
              "BPCOF", "BGT", "BMTL", "BFM", "BSIT", "BPAC", "BYIC", "BGS", "BOTHF", "BFO", "CPESP", "CRPA", "CLSF",
              "CPA", "CPVDT", "CPDA", "CCIA", "CAA", "CTCE", "CWB", "CPFDA", "CGB", "CRORA", "CCMB", "CHRVH", "CHGO",
              "CLSE", "CBFN", "CHR", "CKAC", "CCSBS", "CEGI", "CDI", "CMEP", "CSM", "CSBFO", "CCRP", "CORDT", "CRNS",
              "CVS", "CEFV", "CTIDT", "CPUR", "CESO", "CDA", "CGPEE", "CEL", "CLE", "CIGA", "CVA", "CIVR", "CTTNE",
              "CDHT", "CDH", "CSCS", "CCI", "CLSJ", "CTC", "CRP", "CIS", "CHDAC", "CPP", "CCCB", "CVQ", "CEF", "CCCES",
              "CMRIP", "CTIB", "CENIW", "CRDP", "CBL", "CBORS", "CCM", "CPAPB", "CLGR", "CYEGH", "CETV", "CBB", "CDE",
              "CCOO", "CMSOR", "CQS", "CGT", "CSRSA", "CTLLT", "CWSLI", "CFJVC", "CNFP", "CME", "CPS", "CPCN", "CSN",
              "CSDT", "CDCP", "CER", "CHPAL", "CSIMS", "CSVRS", "CJCR", "CSLRC", "CSICI", "CDCPH", "CJJF", "CLC", "CHU",
              "CMCV", "CPIV", "CSDW", "CVRC", "CWE", "CGBIV", "CBPVF", "CCDTM", "CSXH", "CMEEG", "CTOS", "CWCA", "CCP",
              "CWA", "CRDM", "CARON", "CSCK", "CLRSD", "CNNBP", "CGP", "CQMSO", "CBPL", "CIA", "CEZAS", "CICD", "CPBPR",
              "CNWEI", "CPFPV", "CMP", "CPGH", "CBPSI", "CFFMC", "CBIPA", "CEIS", "CRPMC", "CCH", "CPSM", "CJL",
              "CMISJ", "CRC", "CHST", "CNS", "CWPSP", "CSAI", "COSC", "CZIAE", "CPSH", "CLFFA", "CESP", "CLPFE", "CWS",
              "CPWUA", "CRRL", "CCSJ", "CCT", "CMB", "CALV", "CSHG", "CDLS", "CARL", "CHSO", "CRSRS", "CEM", "CDPB",
              "CSC", "CVJPS", "CTHN", "CRCA", "CFS", "CSGT", "CGO", "CRL", "CIFML", "CSU", "CAHES", "CBCCH", "CSALS",
              "CRAQF", "CAI", "CDOGT", "CECWA", "CBSC", "CJRAA", "CSCR", "COA", "CCLRE", "CABPS", "CIL", "CVC", "CSCH",
              "CETRO", "CUCTP", "CABYB", "CBDO", "CIATR", "CPWEP", "CTFCS", "CAT", "CTKIC", "CRM", "CLG", "CWNIR",
              "CDES", "CMADR", "COH", "CASSM", "CRSW", "CCD", "CHA", "COCB", "CGERE", "CPPAT", "CSL", "CSPFA", "CPCDP",
              "CCRET", "CPF", "CMTDH", "CRRE", "CSGPL", "CGD", "CESJ", "CMTPW", "CDRG", "CBSOS", "CTD", "CSWT", "CMS",
              "CSFC", "CHB", "CTDF", "CJESB", "CND", "CRDS", "CPVDC", "CRF", "CSCC", "CMPD", "CDPSS", "CET", "CRAM",
              "CFOP", "CRMS", "CCDI", "CCOP", "CBHE", "CBGO", "CTA", "CWAS", "CDSSC", "CDXE", "CNOT", "CVHP", "CEC",
              "CZTT", "CAAT", "CELAC", "CMFP", "CPEE", "CMCNA", "CBWE", "CLPA", "CMTPT", "CBSD", "CDT", "CIFM", "CSPMQ",
              "CHAC", "CMFO", "CFTS", "CEEN", "CAFLA", "CPMA", "CCWP", "CJICL", "CFKIE", "CFDC", "CBAM", "CMDA",
              "CLIAM", "CPPRM", "CSH", "CICW", "CBS", "CFAAC", "CSE", "CMAVD", "CWCS", "CPPN", "CJER", "CRB", "CABRM",
              "CGSRI", "CPGC", "CMW", "CHCID", "CRSFE", "CTLC", "CMWE", "CBI", "CFDSB", "CMSBL", "CFEHC", "CGGW",
              "CCISN", "CNE", "CJFCA", "CLB", "CAATR", "CSICS", "CADLS", "CAB", "CAS", "CJRIE", "CISL", "CFSPP", "CEAO",
              "CPCEB", "CAPE", "CRCMI", "CLOC", "CPEL", "CUSGT", "CMPSW", "CDU", "CSMLI", "CCVA", "CPC", "CPMCC", "CRA",
              "CPE", "CMPO", "CWRCT", "CRG", "CNC", "CTP", "CRBDO", "CRTF", "CASOL", "CCUA", "CPDGE", "CTMFT", "CPMP",
              "CSDCL", "COPBN", "CDRIC", "CIIDO", "CMEI", "CSP", "CGSS", "CRTE", "CTVZV", "CPODM", "CUC", "CLD",
              "CMPCS", "CRLL", "CTTGM", "CEHBJ", "CFO", "CABLA", "CHLI", "CBTCC", "CDTAC", "CBP", "CCMGS", "CBCPL",
              "CFFP", "CKTEW", "CMPP", "CAL", "CACO", "CFMTG", "CRES", "CIMWR", "CPBM", "CTHFW", "CBSH", "CEV", "CIOI",
              "CRBC", "CAP", "CQDE", "CSG", "CTRTT", "CFIPM", "CPTTS", "CGEB", "CJG", "CSPBW", "CSCAS", "CIC", "CLBPY",
              "CCE", "CLLEW", "CAGW", "CCMBS", "CPERH", "COSE", "CDAP", "CSRC", "CLJL", "COPCA", "CEP", "CFD", "COD",
              "CWIH", "CCW", "CTI", "CBHFS", "CSPE", "CQVA", "CFTOA", "CCF", "CDS", "CCHCA", "CBA", "CBC", "CMHBP",
              "CAPP", "CGR", "CEEA", "CPM", "CVB", "CGA", "CEW", "CGCUS", "CLCC", "CRV", "CBMHC", "CDOE", "CSLSA",
              "CSEPC", "COPFF", "CRFE", "CPOE", "CTM", "CSTHS", "CSFND", "CMPG", "CIW", "CCGM", "CST", "CTH", "CQSS",
              "CEBC", "CSROE", "CVSEC", "CREVH", "CAAA", "CBDEC", "CJPDP", "CFF", "CTHR", "CJBD", "CRCFJ", "CLV", "CAC",
              "CCC", "CCMI", "CBU", "CPCE", "CSSM", "CQCA", "CSV", "COR", "CBSCA", "CEBTL", "CSS", "CFTCR", "CACW",
              "CBEPE", "CMRS", "CERDT", "CESBS", "CVPE", "CSSS", "CEARG", "CFA", "COSAF", "CPPCB", "CMV", "CCCD",
              "CCTES", "CBAVL", "CSMDH", "CWMI", "CCHAM", "CESK", "CPSL", "CBTBS", "CTVSC", "CUS", "CEPII", "CPH",
              "CAAF", "CAVG", "CELHC", "CRD", "CTS", "CPUI", "CMFD", "CSPB", "CSEP", "CSSH", "CUSC", "CGDLS", "CFN",
              "CSTVM", "CHC", "CTSDT", "CPGP", "CRS", "CSRUV", "CEPR", "CBHR", "CBG", "CBR", "CPI", "CCS", "CMTMT",
              "CTSRA", "CLAM", "CCR", "CSKS", "CDND", "CIDO", "CPCH", "CPSO", "CICT", "CSF", "CPFE", "CIT", "CDC",
              "CFGAI", "CEHED", "CGS", "CCL", "CSAF", "CTRM", "CJC", "CFB", "CAE", "CHE", "CPPR", "CHDRP", "CAF",
              "CRWF", "CPO", "CCCCA", "CKRR", "CROS", "CSLC", "CCPL", "CCIM", "CSCA", "CPSOJ", "CMAMC", "CAGPU", "CABP",
              "CATHM", "CSFB", "CMIID", "DLRMT", "DTEF", "DMQS", "DLIR", "DCE", "DTME", "DOWP", "DFAIC", "DSSES", "DSM",
              "DMRI", "DABE", "DBS", "DMSL", "DRN", "DPP", "DPC", "DCBCL", "DCSH", "DAPG", "DDG", "DNPFF", "DSBL",
              "DPHM", "DHB", "DIU", "DCLVI", "DTG", "DPTSS", "DRVO", "DAIDD", "DSB", "DAFRS", "DAISR", "DBSFE", "DCEPH",
              "DIPDS", "DDERP", "DRODR", "DIB", "DPRR", "DBC", "DTGTV", "DURM", "DUE", "DVWT", "DDBAO", "DSRCD",
              "DDMDQ", "DHCH", "DBSCL", "DMPC", "DCCDP", "DSRN", "DTS", "DSA", "DRC", "DFF", "DTSUP", "DASO", "DSIL",
              "DGEDP", "DJS", "DCB", "DTFFS", "DDK", "DLISC", "DCKCS", "DHD", "DTLNB", "DJAV", "DCGT", "DMOTP", "DRMTD",
              "DWG", "DOFFS", "DISH", "DLMD", "DPGRO", "DSDM", "DCMVC", "DPCUR", "DEDHS", "DYCSP", "DWM", "DDCC",
              "DSSI", "DTRP", "DFWP", "DSSDI", "DERP", "DFD", "DSICM", "DMC", "DMCNJ", "DTSV", "DVSB", "DAI", "DNCV",
              "DSHMD", "DBSPP", "DHKD", "DPV", "DAMS", "DKG", "DRRFC", "DHLS", "DPTCC", "DMS", "DPBIH", "DLAUA", "DRD",
              "DCS", "DCDSS", "DCVTC", "DNAHV", "DMSA", "DIF", "DSP", "DSMA", "DTSSH", "DNV", "DAO", "DCM", "DSEL",
              "DDOG", "DGBRU", "DKTC", "DPPP", "DSS", "DBH", "DPDJI", "DCMIE", "DVMLF", "DLRCL", "DPCTO", "DRSBR",
              "DRSWD", "DCMS", "DPE", "DGLRA", "DAC", "DIP", "DPBI", "DAB", "DBEC", "DEGJ", "DGE", "DLA", "DCCTD",
              "DDC", "DPB", "DHNW", "DPOV", "DSR", "DVPD", "DTES", "DTMDH", "DBEBA", "DASAT", "DSO", "DCCFC", "DBCWS",
              "DCCOL", "DCCT", "DWPC", "DDAS", "DBSE", "DMTM", "DFC", "DTH", "DGH", "DDDHR", "DBFAA", "DBSC", "DCMP",
              "DTSH", "DFCLO", "DMBR", "DHM", "DIS", "DHMS", "DSRP", "DICPA", "DUTS", "DPWIH", "DCA", "DTMKB", "DECIC",
              "DRT", "DTPEA", "DENLB", "DIED", "DOSOK", "DSCSA", "DPVGR", "DMJR", "DBT", "DMTL", "DPDB", "DPA", "DOSTP",
              "DLSP", "DMLA", "DRRIT", "DBPW", "DGMDR", "DMRH", "DTD", "DUIAT", "DEML", "DPBCE", "DPF", "DMSB", "DIFA",
              "DAAHD", "DEH", "DAA", "DEW", "DPL", "DSMF", "DTC", "DWW", "DEMUA", "DERPB", "DSD", "DESS", "DRSR",
              "DAWSG", "DCAW", "DDTSE", "DOVAA", "DRFJB", "DKFP", "DOTC", "DRSFE", "DRW", "DSE", "DRAI", "DSTER", "DCF",
              "DAADS", "DCADE", "DIFJ", "DDLS", "DSVT", "DUJT", "DJPT", "DPCD", "DCLF", "DPPN", "DRML", "DCFE", "DTPD",
              "DQOA", "DMHA", "DHEDC", "DEVTD", "DPSL", "DWR", "DVP", "DYP", "EBPMV", "ELA", "ETE", "EATLU", "EAB",
              "ECAR", "ESL", "ETSG", "EAIH", "EGBT", "EDT", "EBEBD", "EHMA", "EML", "EAVCG", "ESARW", "ETAG", "EODSP",
              "ESTOP", "EAT", "ERBPW", "EUP", "EPA", "EJT", "ESW", "EBPOL", "EIEFJ", "ECLD", "ELV", "EWSEV", "EYE",
              "ESPSS", "EAPP", "EARA", "ESQ", "EVEA", "EIIIA", "EEB", "EMII", "EVA", "ETB", "EMDCP", "EBTA", "EAIRD",
              "EDAMR", "ESMCC", "ESDT", "ETD", "EACBW", "ECAOS", "EPVNI", "EMSCA", "ERRR", "EDFCS", "ESR", "ESTMC",
              "EPEW", "ESMCJ", "EMP", "EHVT", "EWBO", "EAA", "ERT", "ERCO", "EMTTS", "ECS", "EFCHR", "EGLF", "ENE",
              "ESN", "EPZR", "ECIH", "ECI", "ECAWS", "ETDL", "ECRTA", "EPVB", "EPSM", "ESRB", "EECJ", "EGBLS", "ERABA",
              "ESGN", "ELSV", "ESDCF", "ETCC", "ETF", "ERPHS", "ECT", "EACIC", "EFMP", "EJAP", "EUPPC", "ETESM", "EID",
              "EAASM", "ECSS", "EFBCH", "ECIRP", "ECHR", "EPSS", "EAM", "ECC", "ESPTS", "EEMD", "EBLUG", "EODCE",
              "EBKLG", "EMBP", "ECMWT", "ESPWO", "EELF", "EIG", "ERE", "EORNE", "ESPHD", "EIMSF", "EMNP", "EOUKB",
              "EEPR", "EEL", "ECRR", "EAZ", "EIS", "EPL", "EPCG", "ECAE", "EJH", "EVGP", "EFII", "EMHA", "EMGMI",
              "EMSLG", "ESAME", "ERRB", "EFE", "EPG", "ECLLI", "EIF", "ETRS", "ESMS", "EDMA", "EVL", "ECB", "ESCC",
              "EMC", "EDTG", "ESTS", "ETAAW", "ESO", "EMASC", "EAPC", "ECSC", "ECPR", "EEEHA", "EDC", "EYRE", "EFHG",
              "EFM", "ETEP", "EAD", "EZLR", "ECL", "EMAE", "EPM", "EAEMT", "EIL", "ERTBS", "EGPU", "EIO", "EMPI",
              "ETUK", "EBER", "ECSAB", "ESF", "EZPAW", "EJEHS", "EAN", "EIW", "EIM", "ETABM", "EECCD", "ENGPF", "EJG",
              "EPIBT", "EBGA", "ELS", "EMEC", "EIBCW", "ECLPG", "ESS", "EPD", "EACBT", "EBCMC", "EJA", "EPS", "ECA",
              "EHDFP", "EWCLR", "ECSMW", "EAY", "ERDCU", "ESVPC", "EPN", "EPIB", "EBB", "ESC", "ELCEB", "EWWOC",
              "EBACB", "ECLA", "EWCCA", "ETT", "ERP", "ENCBT", "ECFA", "EWCIC", "EWRS", "ETCG", "EFRCS", "EOHGA",
              "ETCIO", "EDH", "ESA", "EUOTC", "EBLWP", "ESTIT", "ESLC", "EEPD", "EFS", "ERQR", "ELR", "ESAC", "EMRMC",
              "EHEDT", "EIE", "ERS", "ESM", "EFFS", "ECIR", "ERICD", "EDIC", "EIPE", "EABIA", "ETDP", "EAI", "ECDT",
              "ERLIH", "ESIDP", "EOOK", "ESCHC", "ECF", "EMBMI", "EMAC", "ETRC", "EWC", "ETDTC", "EMSCF", "ETGI",
              "EMTI", "EHC", "ELM", "EVPJ", "EMRI", "EAMDO", "ECRCT", "EMSNE", "FRM", "FBB", "FDC", "FBPRH", "FWNT",
              "FVI", "FACSF", "FRS", "FBED", "FWTAV", "FATC", "FVMMC", "FCSC", "FNP", "FTNL", "FCS", "FSS", "FLCEC",
              "FUDI", "FNRK", "FTD", "FRMHT", "FSSH", "FTLM", "FAH", "FFD", "FGC", "FAIPC", "FIT", "FTPES", "FPS",
              "FSR", "FTNC", "FCCC", "FPASP", "FSSC", "FGSD", "FRTRF", "FCRC", "FEMKH", "FOAC", "FWLM", "FSHS", "FSAB",
              "FWM", "FWCS", "FTPJB", "FHMGS", "FTN", "FVAI", "FBSER", "FFAMF", "FAI", "FENCC", "FADP", "FBRBP",
              "FAFGC", "FSCF", "FAAE", "FDFAR", "FNB", "FCE", "FRFPT", "FPFFS", "FSC", "FANGF", "FALP", "FDM", "FEV",
              "FMSN", "FRAVO", "FRC", "FSHEC", "FQCOE", "FOCC", "FBDLI", "FTRDB", "FSSAP", "FBS", "FLNF", "FOPJ",
              "FGAOG", "FCPTF", "FWSBA", "FPTRG", "FISRB", "FSCE", "FIFS", "FOKV", "FPI", "FSTSR", "FQEA", "FFBAM",
              "FLVT", "FEE", "FSPSC", "FAIL", "FPTF", "FDUWF", "FEWS", "FSAF", "FSOC", "FFSC", "FPCCB", "FAEL", "FFRBR",
              "FBRRR", "FEPCI", "FMF", "FCMR", "FIH", "FWBD", "FMPSP", "FPTCF", "FVE", "FAWG", "FSP", "FMI", "FSRBO",
              "FMVSG", "FCOGC", "FLSD", "FOLSL", "FSBI", "FTMP", "FGORV", "FCM", "FVWOM", "FPCBR", "FSLLB", "FLVHE",
              "FBI", "FAE", "FFUES", "FMSCM", "FASA", "FCJ", "FARB", "FCK", "FCSM", "FRN", "FLDT", "FEPC", "FCCTR",
              "FEC", "FRE", "FSF", "FCB", "FCDBW", "FPCAA", "FTS", "FCVL", "FDMGH", "FSI", "FASHB", "FEFI", "FVA",
              "FISR", "FWMPN", "FEEL", "FASAF", "FBWD", "FWIR", "FGSRI", "FMORD", "FBC", "FCR", "FMATB", "FABS", "FFB",
              "FSD", "FSEB", "FAEP", "FDRT", "FFA", "FWIRA", "FIA", "FGFC", "FMHVH", "FFIEL", "FDDG", "FTW", "GVMTT",
              "GWBB", "GMOM", "GPRT", "GWCCA", "GWT", "GCC", "GAIPB", "GWVS", "GFVE", "GHE", "GBFD", "GACIB", "GRNSC",
              "GAI", "GAD", "GBSSE", "GCPWA", "GCAM", "GWSMP", "GCM", "GHA", "GAFRT", "GAA", "GFT", "GSD", "GTB",
              "GLMDR", "GRTLE", "GHT", "GDLMR", "GCDQP", "GDTI", "GLA", "GQMSO", "GNCP", "GTGJ", "GDBDT", "GMCI", "GCB",
              "GFA", "GMA", "GRIWM", "GMMA", "GBS", "GTF", "GBTS", "GHFG", "GBM", "GCG", "GEVM", "GER", "GLS", "GAE",
              "GLRAT", "GOTW", "GDP", "GARJY", "GGRI", "GAF", "GCAS", "GAATH", "GTS", "GBCAW", "GDMRP", "GTAD", "GPEM",
              "GSCMI", "GCCE", "GCVP", "GMMD", "GEE", "GIBTB", "GUBT", "GWB", "GSR", "GLSD", "GEM", "GTD", "GHHMD",
              "GSBMB", "GFD", "GPRO", "GCS", "GAIR", "GCRM", "GFO", "GBI", "GMTR", "GPJ", "GAS", "GPPAT", "GPB", "GVPE",
              "GRIID", "GBD", "GJOC", "GFC", "GPDS", "GTN", "GSUS", "GSF", "GCCB", "GCPA", "GET", "GWTMT", "GDTDS",
              "GDABL", "GHESF", "GYM", "GSEI", "GFCS", "GGRHE", "GNKPQ", "GPUDA", "GAAHD", "GHPPS", "GVL", "GCRC",
              "GCSE", "GPCFU", "GNIPC", "GWI", "GRSBD", "GCABS", "GPCVI", "GBRPT", "GAKM", "GMIIS", "HUGM", "HCSV",
              "HFCC", "HPDJ", "HAIL", "HBD", "HODV", "HELEP", "HRBH", "HSS", "HPE", "HEM", "HMCPU", "HDT", "HISPG",
              "HOMMH", "HRDLL", "HOBRF", "HLSAO", "HPSID", "HIEC", "HODTR", "HAPR", "HPVM", "HRCPJ", "HTAHC", "HAS",
              "HHFIF", "HFEF", "HDA", "HHEI", "HIC", "HWDPH", "HTNH", "HET", "HEJB", "HPD", "HNWFT", "HCLEA", "HEHS",
              "HHT", "HBWSK", "HTER", "HRSA", "HMCS", "HIIP", "HPT", "HDOS", "HIVCL", "HEFP", "HPA", "HFWS", "HGNO",
              "HDBP", "HSI", "HTCSB", "HSOS", "HTAEA", "HWCCE", "HCB", "HBBA", "HIS", "HFP", "HRSM", "HCRVP", "HEEEG",
              "HIL", "HFC", "HNTCD", "HLCEM", "HSB", "HBNPA", "HDDE", "HPMR", "HABPB", "HMKM", "HBPCC", "HVPAC", "HFAR",
              "HTGLT", "HCAAD", "HMIA", "HMBV", "HCSF", "HSF", "HLIMB", "HMM", "HJRT", "HMDA", "HARIP", "HAM", "HCSPB",
              "HDAS", "HFTDA", "HDHSM", "HACA", "HCIPC", "HWCMC", "HFRS", "HLP", "HRT", "HRCF", "HRFDB", "HAPBW", "HGS",
              "HLLS", "HBI", "HSWPB", "HTAN", "HPS", "HIFFC", "HNEVI", "HOV", "HWGV", "HDKEM", "HBARF", "HHH", "HAH",
              "HOB", "HCENC", "HETA", "HDAR", "HOTIS", "HJM", "HPP", "HSSS", "HGM", "HIGAN", "HFCN", "HRA", "HCSST",
              "HGHM", "HLPN", "HWBF", "HLCEA", "HFE", "HSMN", "HFFIL", "HPW", "HAPH", "HCF", "HERWE", "HPABC", "HCVWD",
              "HCC", "HEET", "HSQAC", "HSOC", "HSMR", "HRO", "HCIHS", "HPRWM", "HSE", "HSBP", "HTC", "HAPF", "HTA",
              "HRHIC", "HVLS", "HDM", "IBPT", "INCMS", "IAWPS", "IGNCC", "IRAF", "ICIPB", "ILUES", "IPAA", "ICB",
              "IWIF", "IDAGN", "ICAEE", "ISNC", "IFW", "IRSW", "ITSOR", "IMAST", "IDVIG", "ICEIB", "IGC", "IPL", "IAOI",
              "IGTD", "IRD", "INEA", "INO", "IDHP", "IMH", "IRH", "IVCLD", "IRC", "IBP", "ISSSD", "IBTC", "IMCD",
              "IASWR", "ISRPR", "IBPGB", "ISSG", "IBUDT", "ICAD", "ICAI", "IVI", "ICPEO", "ICOR", "IFMP", "ISSS",
              "IJARB", "IFY", "IIEDA", "IFRC", "IPINE", "IED", "IAJP", "IMJ", "IRUGI", "IAS", "IHRAR", "ILEA", "IISCP",
              "IBDRM", "IRP", "ISOI", "ISD", "ISA", "IAP", "ICD", "IRBVR", "IBR", "IIW", "INS", "ISP", "IORC", "IOB",
              "ILVRU", "ITC", "ICOCA", "IAPN", "IHM", "IWT", "IHSAN", "IWPAP", "IWCF", "IFE", "IQRSF", "IAC", "ISVGP",
              "ISLCC", "ISARV", "IDTMC", "IPC", "IETPH", "IMCGG", "ISCY", "ICRR", "IEJ", "IOCSC", "IOASS", "IIACP",
              "IPBC", "IGCA", "IPGU", "ILCEE", "IFEP", "ICTCR", "IMDE", "IMIS", "ILWER", "IASDJ", "ICPMB", "IGCTS",
              "ILOTP", "IEUE", "IOIS", "IMDAB", "INCSP", "ISM", "IFTV", "IDE", "IGP", "IDA", "ICCWC", "IOHAC", "IDFDM",
              "ILR", "ILHSP", "ISF", "IBCCU", "ICC", "ISS", "IUW", "IARWP", "IFU", "ISRME", "IARSO", "ICPM", "IFR",
              "IRJTC", "IBTE", "IVO", "IDSBF", "IRB", "IRW", "IRASL", "IVR", "ICEC", "ILL", "IPRPW", "ICBRT", "ISAG",
              "IDBOA", "IDBBW", "IRCGR", "IVDW", "IVALN", "ICDCD", "IPVIC", "IQCTC", "IASFV", "IRA", "ILCTA", "ICDLH",
              "INAC", "IJB", "IAV", "IFEA", "IAPA", "ILTCC", "IMR", "IRRS", "IYV", "INRE", "IICAS", "ILVB", "IWML",
              "IPTBR", "IVC", "IPDST", "ICAPD", "IRLI", "ISLBO", "ISMS", "ICPAC", "ISMFI", "IVRA", "IAA", "IGS", "INV",
              "IDECT", "IAEA", "IWSB", "IRSE", "ILAC", "IPWDA", "ISE", "IAHD", "IKB", "IBAA", "ICCPA", "IECA", "IFQL",
              "IOAC", "IABP", "ITDC", "ISSIR", "ICEH", "IESP", "IJD", "IMG", "IMCPS", "ICA", "IARWN", "IDPC", "IDPBU",
              "IAIT", "INDP", "IBNPR", "IPGOS", "IDRPR", "IFERP", "IOP", "ISSPP", "IBRT", "IDPPC", "IBDP", "IDM",
              "ICGCM", "IDSS", "ISR", "IMPP", "IRPIR", "IRJ", "IBBK", "IECS", "IMFIT", "IPWFA", "IIS", "ISMWE", "JPHDO",
              "JGKW", "JCWI", "JPC", "JRCC", "JAVT", "JCV", "JGFC", "JAC", "JESSC", "JSDTC", "JMCD", "JERDG", "JPWSA",
              "JHUPW", "JON", "JHD", "JLHS", "JPPE", "JDW", "JWID", "JPALS", "JCHCH", "JCPPT", "JHEWI", "JPT", "JPUE",
              "JIMBA", "JRDS", "JTCB", "JWGL", "JGJV", "JMR", "JSMS", "JECP", "JEES", "JIBM", "JSB", "JBICT", "JBP",
              "JTR", "JHCB", "JABEW", "JCRM", "JGCCG", "JTDN", "JBRFP", "JSJ", "JWOSB", "JSBC", "JTC", "JSI", "JAV",
              "JPEA", "KCRSS", "KSLTB", "KPU", "KWY", "KRC", "KSLRC", "KFG", "KPLRM", "KTBPM", "KAD", "KBG", "KKA",
              "KNNBC", "KRI", "KWR", "KPDC", "KCRV", "KFS", "KISER", "KLA", "KMTVS", "KPW", "KRD", "KDOAP", "KGRA",
              "KWSSD", "KCPM", "KWF", "KCVEM", "KDC", "KELS", "KTIB", "KSDAJ", "KDHI", "KGMMA", "KKPS", "KLC", "KTRS",
              "KCHT", "KLBT", "KAC", "KGFAN", "KSRF", "KOAU", "KSSP", "KTBOS", "KSE", "KTAP", "KIFLP", "KSS", "KMBY",
              "KAFVS", "KGUL", "LFRSR", "LCED", "LHDRL", "LPF", "LEGSS", "LBACM", "LST", "LSC", "LBSD", "LPPJ", "LSM",
              "LDG", "LBDT", "LVOL", "LNAP", "LCCPP", "LCSA", "LABW", "LDCS", "LJC", "LFCSE", "LRRTW", "LCCA", "LKEA",
              "LGI", "LPMT", "LOWM", "LDC", "LAEP", "LITB", "LTE", "LVCS", "LAIH", "LHNG", "LTRCH", "LSDMS", "LOPC",
              "LDIB", "LAM", "LPCBS", "LDIE", "LTP", "LEIO", "LFRCD", "LIMA", "LCAEP", "LPMJ", "LTS", "LPL", "LEBI",
              "LSGS", "LMBDW", "LBSBC", "LHFP", "LSS", "LBT", "LFFAA", "LROFS", "LSDHR", "LPB", "LFWS", "LGCV", "LCOP",
              "LSH", "LHGHC", "LSFSE", "LISA", "LMGB", "LRGSG", "LDECH", "LLWDW", "LPHSP", "LMRBG", "LVIW", "LRJM",
              "LBTCS", "LJBAF", "LHCG", "LRC", "LOERP", "LSFSR", "LFS", "LRS", "LTCH", "LES", "LMD", "LICCD", "LMGAE",
              "LMT", "LRFC", "LTDBD", "LTFI", "LSDEP", "LSHEP", "LUW", "LCS", "LHU", "LIRPG", "LTV", "LTMSG", "LCCAS",
              "LDERS", "LORDN", "LBE", "LMPD", "LPGRV", "LPR", "LSSC", "LBMED", "LBFM", "LSSLL", "LAA", "LMDDE", "LOAS",
              "LTRSM", "LCYEG", "LWHGP", "LEP", "LCC", "LMS", "LOAH", "LMGCP", "LRRS", "LDSA", "LDPV", "LSAEA", "LCR",
              "LETD", "LRA", "LGMB", "LBEA", "LCG", "LCCAD", "LSCA", "LCPTT", "LCPMV", "LFLOG", "LRQ", "LCY", "LFTS",
              "LGWCS", "LHCA", "LHEA", "LAR", "LERPE", "LPHSC", "LRSNE", "LRL", "LFMAT", "LDPK", "LRJ", "LSB", "MBLBL",
              "MCTLP", "MCDTP", "MCGPR", "MVRS", "MMDC", "MTIC", "MKAMC", "MSRC", "MRSP", "MESCP", "MCIM", "MBPC",
              "MAB", "MMS", "MVOS", "MRHD", "MZCG", "MACBJ", "MCC", "MAPTD", "MAVT", "MDRR", "MTSS", "MWC", "MPFPE",
              "MRSU", "MVG", "MRC", "MDPYO", "MCPS", "MHC", "MSFT", "MDME", "MXS", "MSCR", "MANVN", "MDYEM", "MJRO",
              "MTCCF", "MRK", "MIM", "MAC", "MCITF", "MTT", "MIF", "MAERD", "MCI", "MLS", "MAASS", "MDHD", "MSPE",
              "MCRN", "MDM", "MEAC", "MNREB", "MBUTR", "MEDMW", "MFS", "MDO", "MTI", "MPH", "MCCPS", "MTG", "MRUSR",
              "MLCQS", "MPBTU", "MFPES", "MCASM", "MACP", "MVT", "MRFUC", "MAP", "MBM", "MINAS", "MTBF", "MSD", "MCDGA",
              "MPRI", "MESHV", "MCP", "MUC", "MAAW", "MCCC", "MOG", "MRROE", "MFSTI", "MTSSV", "MBAGA", "MPB", "MTE",
              "MBFIM", "MHN", "MDFI", "MRCNS", "MPP", "MBSC", "MDSR", "MLSA", "MCL", "MBSD", "MERDS", "MCRCI", "MNP",
              "MSB", "MDC", "MEEA", "MPADC", "MQYI", "MTRM", "MPDR", "MTC", "MCPP", "MSA", "MEPF", "MNPSN", "MEAI",
              "MPEVS", "MHWAA", "MPHM", "MFFPA", "MIMF", "MCV", "MDFM", "MIE", "MPS", "MEDS", "MUP", "MEVCW", "MNDIP",
              "MTCC", "MSAF", "MSET", "MTYA", "MJE", "MFCSS", "MFIR", "MRLS", "MER", "MFN", "MLSS", "MSH", "MRBE",
              "MREDJ", "MCW", "MSL", "MMAR", "MSSL", "MCR", "MDJ", "MICD", "MVGC", "MWSSA", "MAMC", "MSRIS", "MLSSF",
              "MMCA", "MAGA", "MGDW", "MSFR", "MAD", "MPAI", "MSHM", "MHFS", "MSC", "MSSAS", "MSAH", "MVHD", "MAIL",
              "MIPS", "MBV", "MARN", "MSADP", "MWCA", "MBP", "MBKD", "MSF", "MFC", "MMLFM", "MECCA", "MICW", "MTGX",
              "MCT", "MKV", "MISC", "MSPEF", "MBARC", "MABGW", "MEB", "MTSFG", "MBRE", "MEL", "MII", "MAHP", "MBS",
              "MCYS", "MJU", "MTA", "MTSB", "MIELP", "MIFDL", "MRCRD", "MSU", "MEDDS", "MSS", "MCSA", "MIDE", "MIS",
              "MTR", "MCNCM", "MCDIC", "MPCSP", "MPGGP", "MDEBC", "MHPMA", "MPCSR", "MGNBF", "MDSP", "MMSC", "MOT",
              "MRPHS", "MDS", "MZM", "MBTWB", "MAEET", "MEASC", "MCM", "MGLCN", "MPCG", "MONBB", "MSBC", "MADW", "MTFP",
              "MFEA", "MSM", "MHDDP", "MLLD", "MDSCE", "MESD", "MSSC", "MCAT", "MTS", "MTMAS", "MHECC", "MPRSC", "MSP",
              "MAFG", "MES", "MJHP", "MMNIL", "MDAJE", "MMBE", "MSPC", "MMQ", "MNCB", "MRTMI", "MSE", "MBE", "MPPCG",
              "MRCB", "MPFAF", "MWPFS", "MNV", "MSAT", "MBPPN", "MDEKW", "MOTAV", "NJH", "NBED", "NBIIC", "NFCRV",
              "NCA", "NEM", "NPDAD", "NSCRF", "NOCM", "NCP", "NCPC", "NPC", "NBCM", "NEP", "NJC", "NAJE", "NIDTC",
              "NLO", "NMR", "NIS", "NSS", "NCDPI", "NDFSC", "NES", "NTCCS", "NTD", "NOCCF", "NEVAR", "NSPGD", "NAHS",
              "NRAT", "NSAMW", "NSE", "NASJ", "NFVB", "NSHP", "NSP", "NMIS", "NRLS", "NGD", "NSHCA", "NEC", "NVS",
              "NIRP", "NCSC", "NPUTF", "NHE", "NDCIS", "NDAB", "NGTS", "NDC", "NCL", "NDMBA", "NIGLO", "NCRPR", "NMC",
              "NSEE", "NPADA", "NPMR", "NFS", "NOU", "NTT", "NMSAF", "NEPN", "NPIH", "NBNL", "NBP", "NPSMB", "NCBCE",
              "NVAP", "NUFLB", "NIMS", "NACDB", "NBT", "NFNLE", "NMPA", "NAPS", "NADT", "NGPK", "NPHD", "NNDHE",
              "NPAPR", "NRAE", "NCBMA", "NMSCE", "NSECA", "NSTMS", "NAWH", "NIFE", "NBHF", "NSPAS", "NUAH", "NOC",
              "NAHLG", "OTAEC", "OMM", "OECD", "OPI", "OCCAP", "OIW", "OIP", "OXSDB", "OAMNC", "OGC", "OPT", "OBERC",
              "OAVA", "OIN", "OEFC", "OMTSF", "OPS", "OPA", "OPMA", "OBCEA", "OPSH", "ORRR", "OWT", "OESP", "OGCL",
              "OCDPH", "OICS", "OIHP", "OMAGC", "OBSIN", "OKR", "OPRM", "OEP", "OHC", "OOLPP", "OPFRD", "OSSOF", "OCI",
              "ORENA", "ODI", "OIT", "OAEC", "OTNE", "OBLR", "ODBAR", "OTF", "OFRP", "OUGM", "OASS", "OCD", "OBSNA",
              "OOR", "ONA", "OSDL", "OIAEA", "OPMN", "OSWJS", "OCG", "OSMT", "OCRPP", "OEE", "OBLD", "OECIO", "OIMO",
              "OIL", "OOJ", "OTLA", "OPNE", "ORACP", "OCLR", "OVC", "OEHTC", "OSTF", "OTS", "OBAA", "ORC", "OMP",
              "OMDR", "OTR", "OBW", "OMLD", "OPIPD", "OEIS", "OFM", "OPB", "ORT", "OTRA", "OIRGP", "OBCS", "OCT",
              "OPSC", "OMPAR", "OMSO", "OSE", "OEW", "OBP", "OSOWS", "OAG", "OMKQA", "OWCS", "ODH", "OSCP", "OAL",
              "OGAAS", "ORI", "OCSSC", "OSSS", "OHTAM", "OAB", "OEJ", "ODDA", "ORRER", "OMI", "OBS", "OAAI", "OEL",
              "OMPR", "OMTC", "OSVG", "OVDF", "PCCBS", "PCBA", "PEJA", "PRSRD", "PPH", "PWPR", "PETDC", "PMM", "PDB",
              "PCD", "PCN", "PPHBM", "PUTP", "PAAF", "PVR", "PHSCB", "PFS", "PIIRT", "PAAT", "PNBC", "PWIT", "PPOS",
              "PEH", "PCTRP", "PCS", "PHPSF", "PJBPF", "PSHST", "PNEA", "PGB", "PSW", "PRLM", "PTESD", "PLA", "PBP",
              "PPCJ", "PPJAV", "PWSB", "PDSP", "PIIC", "PTRE", "PTCIC", "PCPS", "PFAFB", "PMC", "PRCLD", "PTASO",
              "PDSCS", "PIRA", "PGO", "PNFP", "PLEB", "PSCW", "PLKT", "PSNW", "PSB", "PSEDT", "PAIM", "PGMNB", "PCP",
              "PPE", "PBPF", "PAES", "POSS", "PGAC", "PWR", "PBICD", "PVGH", "PPS", "PSPS", "PANAT", "PTM", "PIHSI",
              "PPVT", "PASDH", "PIS", "PAW", "PHBS", "PMBR", "PTC", "PWAUE", "PFP", "PCSCA", "PPSCF", "PBM", "PBBH",
              "PCTSC", "PJI", "PLEMB", "PGABM", "PLP", "PRBR", "PLIS", "PNBH", "PBEKP", "PEWGW", "PHSS", "PLPB",
              "PPAWP", "PACIM", "PCCM", "PDR", "PSC", "POH", "PCCE", "PASP", "PSSWW", "PADCU", "PGRT", "PBV", "PFC",
              "PREWM", "PMRIF", "PLC", "PRWRB", "PST", "PSDE", "PTPS", "PMA", "PSGAT", "PAE", "PBES", "PPC", "PPO",
              "PSSA", "PSST", "PKE", "PRCLI", "PATH", "PSTM", "PHSB", "POA", "PPN", "PQA", "PSPT", "PETTT", "PPPFA",
              "PAREA", "PPTP", "PPME", "PTBP", "PCT", "PWSR", "PRLC", "PAC", "PRBEP", "PSTD", "PMCS", "PRCJA", "PTLIB",
              "PCB", "PNIBA", "PWFSW", "PACCC", "PSGT", "PRERM", "PTR", "PDT", "PAO", "PQS", "PWP", "PIBRP", "PRW",
              "POS", "PAM", "PEPTD", "PIR", "PCSIA", "PPBD", "PARKW", "PTPL", "PILG", "PLM", "PBMS", "PSP", "PGUCU",
              "PTVR", "PSDF", "PVD", "PTCFA", "PWC", "PMLEW", "PSS", "PFBPM", "PFBDH", "PCBAF", "PIP", "PEDSV", "PMLP",
              "PSG", "PBTMD", "PDCEL", "POCM", "PCAO", "PRTA", "PHSC", "POTB", "PEL", "PRT", "PVL", "POP", "PRMWL",
              "PIHSW", "PRP", "PSAW", "PVE", "PRMRI", "PBIR", "PIPH", "PPES", "PSSJG", "PCPC", "PPSCS", "PPM", "PCCN",
              "PLPR", "PMS", "PMSR", "PGF", "PKA", "PPSRL", "PSHD", "PWBLS", "PTCLC", "PMSB", "PNRC", "PUD", "PAMLS",
              "PSGWA", "PNICC", "PPWSB", "PMP", "PRPBS", "PAL", "PEACB", "PCR", "PPAGW", "PEHP", "PFHCR", "PAB", "PSLT",
              "PTE", "PATAV", "PWRT", "PBASF", "PPCMC", "PSBI", "PITFT", "PPBB", "PRCSC", "PRI", "PDNGL", "PLMB",
              "PASE", "PIVC", "POC", "PBL", "PWSS", "PFMK", "PBAGS", "PCCSS", "PSQ", "PUHMF", "PTSC", "PFCRV", "PLR",
              "PATFE", "POMDS", "PCSO", "PAK", "PEJP", "PCWOH", "PPFCD", "PDGS", "PAHBS", "PDHMM", "PGADB", "PMN",
              "POSB", "PAF", "PTFV", "PBJ", "PEES", "PVS", "PSF", "PHDTC", "PPETT", "PWBIB", "PSAC", "PHB", "PSDYC",
              "PTS", "PVED", "PCATM", "PUTR", "PTIP", "PGIJ", "PCIC", "PRNC", "PSBC", "PDCLP", "PPSPP", "PPFF", "PFH",
              "PSOS", "PWCBK", "PDW", "PEI", "PIE", "PICL", "PCLCA", "PDSSP", "PDI", "PFBC", "PCHA", "PMNE", "PER",
              "PSBAR", "PTHAS", "PUCIO", "PWEC", "PTD", "PCAE", "PROR", "PCH", "PCI", "PDAIA", "PEAS", "PGAF", "PSI",
              "PCDD", "PDRB", "POCSC", "PAOBP", "PFV", "PIKS", "PLFP", "PQDM", "PRLHL", "PRMC", "PCIM", "PRE", "PAP",
              "PTCP", "PEST", "PPA", "PSE", "PBAG", "PVFHT", "PCRR", "PETN", "PPVRO", "PNMHT", "PQTPL", "PNCQ", "PFPRC",
              "PNL", "PDDSM", "PFST", "PAR", "PYW", "PSTC", "PDS", "PWRKP", "PACFE", "PSDC", "PLD", "PCSCU", "PJTGD",
              "PDCC", "PBSP", "PICSP", "PPLCC", "PCGPT", "PLSG", "PGAGA", "PJB", "PZC", "PDCO", "PBSCD", "PFE", "PNC",
              "PEDJJ", "PMMCW", "PPD", "PBD", "PSD", "PPCE", "PRD", "PHTID", "PSPIC", "PCLAR", "PPT", "PCSC", "PTGMF",
              "PIZET", "PPDTR", "PEHMD", "PCMC", "PPPS", "PRC", "PBCVF", "PPDCR", "PBT", "PPTFS", "PSBS", "PSMBO",
              "PRSS", "PUMT", "PSLTF", "PLPTC", "PSH", "PRCV", "PTGE", "QPGC", "QBMR", "QGG", "QRF", "QEAIS", "QROCV",
              "QSSP", "QSSAM", "QMB", "QLCA", "QTTHP", "QAMM", "QRD", "QWAL", "QIFS", "QDTPP", "QPA", "QCRSD", "QRP",
              "QQTM", "QAOJ", "RRBFT", "RMDAC", "RECB", "ROCF", "RALF", "RIEIM", "RMCDB", "REH", "RERCD", "RDFLF",
              "RBHG", "RLSA", "RSG", "RHIE", "RFS", "RMGM", "REC", "RRI", "RCP", "RDCHS", "RGSI", "RVCR", "RJMBS",
              "RTDP", "RWSC", "RMOSE", "RFD", "RCTM", "RMTS", "RAACS", "RPRNT", "RTLIA", "RPCSS", "RTEN", "RPE", "RPFT",
              "RARTT", "RFL", "RPWOR", "RFCCP", "RDSPC", "RPCB", "RCNEE", "RCBM", "RWRMA", "RCR", "RLT", "RCMRR",
              "RCLMG", "RPDWD", "RDA", "RMBMH", "RSPR", "RCAI", "RRCFR", "RRMD", "RAC", "RMLIO", "RAV", "RHS", "RTCA",
              "RRGE", "RSGAM", "RDTC", "RSCDN", "RPD", "RMRG", "RRAS", "RSMAC", "RFT", "RRPM", "RBI", "REA", "RSUY",
              "RSAGT", "RFA", "ROJP", "RCMBM", "RCTA", "RLWBP", "RTP", "RCJ", "RIBD", "RLPS", "RIH", "RDRRC", "RCWPA",
              "RMVS", "RAEWD", "RDT", "RFCB", "RTS", "RSDCI", "RAISR", "RPP", "RSP", "RARI", "RCA", "RSRR", "RASGD",
              "RDPCA", "RPDFP", "REAI", "RFBC", "RWA", "RLV", "RBCRT", "ROHF", "RRLC", "RST", "RFC", "REOLV", "RRSB",
              "RFMW", "RIB", "RMCTN", "RMED", "RETDG", "RNC", "REAAA", "RDAP", "RHM", "RDJPS", "RECSF", "RGPA", "RMMH",
              "RDRV", "RSCE", "RSR", "RRMW", "RAU", "RSOFI", "RPLPA", "RCCYS", "RSEE", "RDP", "RTLC", "RRSSB", "RTC",
              "RLSS", "RLWTA", "RBP", "RSC", "RHPG", "RIS", "RCO", "RRU", "RSBOP", "RLO", "RSEAA", "RAE", "RTMB",
              "RCSAC", "RAQSD", "RMN", "RBA", "RPWMB", "RCAS", "RCMJD", "RCPP", "RVS", "RDLAC", "RWG", "RMIR", "RTA",
              "RDSO", "RPA", "RTPIT", "REI", "RFO", "RSNSV", "RBS", "RMMNS", "RCFC", "RDBTH", "RTSM", "RRYEC", "RLE",
              "RPOBP", "RPPU", "RIMHL", "RLMB", "RSER", "ROLMR", "RBTR", "RITTC", "RACC", "RAA", "RAAP", "RRSC",
              "RFMAM", "RED", "RER", "RDF", "ROE", "RDJFN", "RDG", "RHCC", "RISG", "RASF", "RGD", "RIGR", "RCB", "RES",
              "RSW", "RPDFG", "RMAD", "RRRM", "RTOI", "RPCJS", "RCFS", "RMS", "RPWFH", "RRTCS", "RTTC", "RPBT", "RSWUC",
              "RCE", "RTDB", "RVTCE", "RCN", "RWV", "RTFM", "REP", "RIAS", "RNFPC", "RMD", "RGMD", "RRA", "REMU",
              "RLAG", "RBDPO", "RINCD", "RMLH", "RPAN", "RNL", "RJI", "RFOE", "RGFA", "RTPD", "RAFC", "RME", "RPVFC",
              "RDPRD", "RPNG", "RVP", "REAM", "RRARC", "RGA", "RASR", "RLCN", "RPC", "RFM", "RHG", "RDE", "RFIH",
              "RITG", "RSRL", "RVWB", "RCSRD", "RRDGM", "RBCSN", "RDCS", "RDPF", "RPWR", "RSSSP", "RMDP", "RCETI",
              "RSCCH", "RAM", "RNU", "RAPCP", "RHSO", "RSB", "RTB", "RGFJ", "RDCL", "RAT", "RPW", "RDJG", "RSCR", "RDS",
              "RSFMA", "RPPL", "RWMO", "RIFNC", "RID", "RPADB", "RKA", "RTSIS", "RCC", "RAALC", "RMTD", "RINTC",
              "RCFCZ", "SCFM", "SHA", "SITG", "SKGFC", "SHCC", "SEL", "SSBOP", "SACSP", "SCEHF", "SSLAE", "SCSK",
              "SBKP", "SJPTC", "STAWA", "SNF", "SAPA", "SIUBM", "SRPV", "SGCO", "SDEAS", "SCTMP", "SEW", "SAJ", "SBFRS",
              "SFCAE", "SLG", "SHIGS", "SMSM", "SEB", "SUS", "SQEN", "SELE", "SRUGE", "STBIH", "STDC", "SJSPS", "SBCG",
              "SBCMM", "SDVOM", "SSIB", "SDPP", "SEPBI", "SFAA", "SCPP", "STD", "STMH", "SLT", "SRI", "SBATM", "SCJ",
              "SGFP", "SAMCS", "SAH", "SKC", "SBRF", "SPFST", "SGCC", "SMAHS", "SOCC", "STSAP", "SESA", "SMAA", "SCQSL",
              "SDWH", "SSED", "SMB", "SCTTS", "SMPIM", "SMCCD", "SCSCC", "SJG", "SSTVA", "SENSS", "SNO", "SAM", "SFSWI",
              "SPPW", "SBER", "SISAC", "SCM", "SEMQE", "SED", "SGTC", "SBPIA", "STR", "SKWT", "SMDL", "SESAM", "SDDC",
              "SFCTG", "STWND", "SHAWF", "SSPCT", "SQPH", "SRBPH", "SVAGE", "SPDI", "SHAS", "SMS", "SHGG", "SFLSC",
              "SWCBF", "SSAN", "SCSLT", "SWSAP", "SHQT", "SGAF", "SCP", "SEOMR", "SRW", "SCH", "SHSP", "SLCE", "SKNR",
              "STF", "SOL", "SPI", "SHSAI", "SDRRT", "SWR", "SCCC", "SSV", "SST", "SGA", "SPGUP", "SIOW", "SMNPS",
              "SPA", "SEF", "SJRSB", "SELC", "SJFA", "SPS", "SDF", "SNJM", "SPPR", "SEVB", "SUOCA", "SOPM", "SML",
              "SPRE", "SDFW", "SUT", "SDPU", "SSCES", "SEE", "SPEJT", "SRIE", "SICDW", "SPAMC", "SCSA", "STG", "SLCR",
              "SWCD", "SSH", "SAPC", "SES", "SRWS", "SBN", "SBV", "SSRL", "SSAC", "SJD", "SNECR", "SSPW", "SAC", "SGCM",
              "SMD", "SLDM", "SVC", "SPDSK", "SSEL", "SSTP", "SRAD", "STP", "SFS", "SMF", "SHAES", "SDWS", "SRVPM",
              "SMACT", "SGP", "SPRG", "SOABI", "SPB", "SLPWF", "SRTCV", "SDBPI", "SBRAT", "SBMC", "SECS", "SSLA",
              "SAPSP", "SLSPS", "SPD", "SOCG", "SHTCS", "SMAD", "SSCP", "SCD", "SMSA", "SSFDM", "SRLT", "SASPP",
              "SHCGR", "SMFTR", "STBM", "SIFCC", "SMCPI", "SQIS", "SUNP", "STE", "SDVVT", "SBQC", "SBPP", "SBDMI",
              "SCADT", "SJH", "SLCM", "SWSCR", "SFN", "SSPO", "SSA", "STCS", "STPOS", "SWC", "SUAB", "SHD", "SEPS",
              "SCKCR", "SIC", "SSDCF", "SBPDB", "SWINP", "SBCCC", "SNDT", "SWFFR", "SRM", "SRB", "SABSF", "SHS",
              "SRMTM", "SCHV", "STMDT", "SGD", "SSEC", "SGL", "SASG", "SLMF", "SREMB", "SIP", "SABV", "SBPI", "SLF",
              "SPJLB", "SPTP", "SRC", "SCIHE", "SBTD", "SSPP", "STKB", "SCDR", "SIM", "SSQR", "SSEFB", "SAL", "SDEC",
              "SSRGM", "SPET", "SGSB", "SSOC", "SCJC", "STUA", "SCFEP", "SDI", "SFSAR", "SAGR", "SLARR", "SEGEI", "SAP",
              "SEN", "SDC", "SDP", "SROV", "SACS", "SEPP", "SAG", "SEIEB", "SETEA", "SRD", "SMAB", "SLM", "SMBP", "SCT",
              "STPMI", "SDROO", "SCL", "SCSPP", "SLPSM", "SAAW", "SWO", "SPWTB", "SDR", "STC", "SVD", "SCMPS", "SCIAE",
              "SOBL", "STLC", "SCS", "SSAF", "SASS", "SJB", "SWMRD", "SIL", "SSTKC", "SAAP", "SAPN", "SSC", "SPEG",
              "SRSCP", "SILE", "SSHDE", "SRS", "SFFRF", "SIWC", "SSCFC", "SSNLB", "SCSS", "SHNF", "SRRC", "SCSSA",
              "SXWHD", "SSL", "SPKJ", "SRG", "SCSC", "SVE", "SCPB", "SVDLC", "SOFA", "SESS", "SSTCS", "SJNMC", "SJIUS",
              "SAS", "SMCCP", "STCBG", "SAD", "SCPIE", "SACLS", "SWRT", "SCCBD", "SBCH", "SFSEI", "SMO", "SJP", "STEP",
              "SASF", "SUX", "SRMM", "SGU", "SECD", "SEJS", "SIVC", "SGBP", "SGPGP", "SFLUS", "SBPC", "SISO", "SRPRC",
              "STA", "STVMC", "STWE", "SIFP", "SBPBM", "SLTV", "SWSSM", "SEEIP", "SREU", "STIN", "STT", "SNTBC", "SCA",
              "SSTAO", "SRGE", "SRH", "SGHA", "SIAC", "SILR", "SPH", "SMEOB", "SSSEP", "STCPB", "SFCBN", "SCEM", "SSHS",
              "SARR", "SHN", "SNEET", "SHM", "SGO", "SUAS", "SELT", "SWM", "SLGS", "SSADQ", "SCB", "SLR", "SAIFA",
              "SLCSD", "SAFAC", "SCDC", "SRCLE", "SKFS", "SWASE", "SSCD", "STL", "SMSR", "SBI", "SPT", "SCLP", "SRPED",
              "SBR", "SAAE", "SRDPP", "SMSO", "SSDWV", "SEDR", "SAT", "SYMS", "SFRA", "SFTE", "SACSI", "SSASD", "SPRC",
              "SSKB", "SRUS", "SCME", "SCMC", "SRBS", "SHPFI", "SALFA", "SFD", "SPC", "SMC", "SIMC", "SISJ", "SKWDT",
              "SECCA", "SCC", "SHFDM", "SITDB", "SQACR", "SLBST", "SPR", "SPPT", "SCCCI", "SGAC", "SPLAH", "SRTTF",
              "SCF", "SMFP", "SDOHM", "SIO", "SRA", "SSI", "SUMC", "SSSOS", "SNFAF", "SGC", "SMST", "SHZH", "SMUA",
              "SOCB", "SAB", "SRDO", "SLC", "SLJ", "SENLF", "SPDP", "SSM", "STB", "SVRP", "SHPU", "SPRV", "SOBRK",
              "STFE", "SMLS", "SBC", "SCEC", "SKCCP", "STCTD", "SBT", "SBEB", "SSFI", "SEP", "SWASB", "SHC", "SCODE",
              "SNK", "SDL", "SHPDS", "SMPCH", "SOI", "SDBGI", "SSD", "SBS", "SBRR", "SDDPM", "SBML", "SABYS", "TGRDP",
              "TSNA", "TEDDT", "TTC", "THPAW", "TIUWF", "TMAOB", "TPD", "TMRC", "TNLB", "TTW", "TQCP", "TCTI", "TDRCT",
              "TDE", "TLCTL", "TSE", "TPPRC", "TCCES", "TCOG", "TLFC", "TFT", "TOG", "TARD", "TBM", "TRVP", "TWCED",
              "TOSFR", "TITC", "TEP", "TPBWI", "TBSL", "TCR", "TAPS", "TADM", "TSLA", "TLSC", "TSFB", "TSAL", "TASDC",
              "TCAWJ", "TSME", "TCSH", "TTCSM", "TCRL", "TIASF", "TSPE", "TDJC", "TBSCC", "THC", "TRDNR", "TNRB",
              "TPCCP", "TEST", "TTCB", "TBRD", "TEG", "TIT", "TAV", "TEAS", "TPRAI", "TRDSL", "TTTC", "TTCR", "TGHHF",
              "TPOE", "TRGS", "TGPCV", "TIBA", "TVGM", "TBVED", "TSCMC", "TPAC", "TAMWR", "TDASC", "TDEN", "TPBO",
              "TBH", "TCRR", "TES", "TFES", "TGRV", "TSNE", "TRS", "TREM", "TESPP", "TRWS", "TCM", "TGE", "TPTWN",
              "TBCPD", "TRO", "TOCMS", "TIRSI", "TAH", "TBPF", "TPB", "TAID", "TMVG", "TCST", "TRW", "TCP", "TTPDN",
              "TSCA", "TGL", "TOSE", "TRM", "TTSC", "TOO", "THMEF", "TSBBS", "TTNH", "TPCRP", "TIS", "TIWLK", "TLC",
              "TMAI", "TONP", "TVE", "TIC", "TSM", "TDCC", "TGM", "TKL", "TFPPR", "TMG", "TTST", "TCPOB", "THFR", "THA",
              "TMCFA", "TAO", "TEC", "TJLM", "TVCVN", "TRSEC", "TRAI", "TTG", "TBGMI", "TBF", "TWB", "TIAF", "TLBI",
              "TAUB", "TSO", "TDCF", "TSIO", "TFBA", "TBPVP", "TEIT", "TREF", "TCDM", "TFGC", "TOA", "TPO", "TUND",
              "TPGBN", "TCS", "TTCRS", "TCC", "TCWC", "TSSMS", "TSCFA", "TSSTD", "TACE", "TFM", "TTT", "THT", "TWV",
              "TALC", "TFAS", "THS", "TPSC", "TRE", "TGAS", "THSG", "TPOC", "TAEDD", "TOF", "TDA", "TOOS", "TSTT",
              "TUBCF", "TSII", "TESDC", "TSDSH", "TNV", "TCCSC", "TSIGP", "TNSRI", "TSATF", "TGOTI", "TAT", "TNLM",
              "TCLHP", "TAD", "TBA", "TBAF", "TIUUV", "TCEU", "TOL", "TSCS", "TMS", "TBPDC", "TIWS", "TMSMW", "TLCNY",
              "TRVAC", "TSW", "TID", "TFAB", "TCCT", "TSGP", "TTTA", "THAPT", "TNPPA", "TULDV", "TSVC", "TDIS", "TSRN",
              "TESCP", "TMCA", "TDVDS", "TAVH", "TPCH", "TAMQ", "TETCS", "TTSS", "TAMGC", "TCI", "TSWL", "TSRR", "TIJ",
              "TCCRI", "TWMAC", "TCDDP", "TITS", "TALBP", "TFSB", "TCBO", "TFBM", "TAR", "TPTE", "TTRFP", "TMR",
              "TCRPW", "TRVAE", "TTCA", "TCFL", "TAF", "TPC", "TLG", "TRSD", "TCL", "TTESR", "TMSE", "TBDA", "UTCTI",
              "UOPR", "UHDSL", "UUSRS", "UBC", "UHPCW", "USPB", "UBP", "UDIAL", "UKW", "UMOFA", "UCRT", "UAE", "UCFD",
              "UAIDS", "ULNPG", "UBR", "UAM", "UBCHT", "UNSCA", "UPQC", "UCLM", "UIPP", "USRJP", "UORCB", "UTA", "USE",
              "UTT", "UTVT", "UCFE", "UCKVL", "UFHJ", "UEOA", "UBM", "UDCVU", "UMA", "UMC", "UCM", "URPN", "ULMFC",
              "UMB", "UCEP", "UFED", "UIC", "UBS", "UKF", "UTDW", "UPJFP", "UMCA", "UPCV", "UPCC", "VESIT", "VISPC",
              "VSQAC", "VBC", "VSC", "VNB", "VOA", "VRDRO", "VCHSE", "VMM", "VPCRV", "VLV", "VSSEM", "VCP", "VWML",
              "VIRPQ", "VCBQ", "VETH", "VFCS", "VPF", "VHTBD", "VLTBO", "VSMI", "VCC", "VISSV", "VVZMS", "VPTFD", "VRI",
              "VPR", "VGOP", "VBCA", "VCIDS", "VFPT", "VPLAC", "VTAA", "VSOSK", "VUAF", "VDBLC", "VRDAD", "VEF", "VHAD",
              "VSNM", "VBBAL", "VST", "VTEP", "VAOHH", "VCW", "VHSBR", "VSS", "VSM", "VAP", "VFSL", "VCVGP", "VCDSC",
              "VOWVI", "VPVMS", "VADLD", "VSP", "VOF", "VBCW", "VSR", "VLLP", "VMC", "VIT", "VEC", "VRFRP", "VTC",
              "VMSS", "VIW", "VESFR", "VUCET", "VSBS", "VVEOT", "VIA", "VCRT", "VRR", "VHC", "VSF", "VIP", "VTG",
              "VIAPP", "VLA", "VNIBE", "VTW", "VPA", "VCWTS", "VIM", "VWSS", "VNWSG", "VPITD", "VRG", "VFA", "VLDTI",
              "VSRA", "VCMC", "VUFTH", "VCTCN", "VPRPM", "VWC", "VADC", "VPB", "VOCRE", "VHCTS", "VPCJ", "VRSRM",
              "VIWCO", "VRD", "VDEA", "VPCIC", "VFOF", "VTEAO", "VVM", "VTAM", "VAGMH", "VGMCF", "VRL", "VSSSB",
              "WPTCH", "WBE", "WCWS", "WCTAR", "WTECG", "WVME", "WSMGD", "WVHM", "WCNL", "WCM", "WCBAT", "WCINS",
              "WEPPA", "WACPF", "WDY", "WBST", "WFC", "WACI", "WFSC", "WCA", "WLGN", "WSPN", "WOC", "WSP", "WASD",
              "WMP", "WWPJ", "WLIA", "WRE", "WARAB", "WSC", "WFI", "WOAR", "WMSSA", "WSR", "WDECC", "WGRV", "WCI",
              "WSLCP", "WLWVL", "WPRPA", "WTR", "WESM", "WCAMB", "WCCG", "WDTR", "WFOS", "WCTC", "WCF", "WFMI", "WGISC",
              "WTP", "WBHML", "WRPC", "WSRRA", "WTAPE", "WMQ", "WSFLD", "WCCQT", "WPR", "WCC", "WDCT", "WAB", "WPECC",
              "WCTTS", "WMHFP", "WBDR", "WHFGM", "WAVP", "WCOE", "WCBMP", "WNE", "WSVW", "WARC", "WPF", "WRT", "WSOTC",
              "WCS", "WCLC", "WSBC", "WCSB", "WWDC", "WMSCP", "WTS", "WECC", "WHSBS", "WULMF", "WBSNM", "WCSIS",
              "WPIIW", "WFAS", "WCNR", "WMW", "WPPJ", "WIC", "WTL", "WPPNG", "WRKCP", "WRHTH", "WPDPW", "WOBKC",
              "WHOCT", "WRDS", "WBD", "WIR", "WSALE", "WASFP", "WDBPP", "WMOHC", "WSDS", "WUR", "WGCC", "WMUJ", "WPCSE",
              "WSMC", "WGBI", "WBR", "WJN", "WPFS", "WPC", "WIRE", "WRREB", "WBEIG", "XFD", "XTM", "YACF", "YDSBS",
              "YCSCC", "YEIMS", "YTM", "YEIO", "YNLES", "ZCSAS", "ZSCP", "ZDS", "ZOPDC", "ZASPO", "ZMSR", "ZPEA",
              "ZLPS"]


def app_specific_user_login(webdriver, username='admin', password='admin'):
    login_page = Login(webdriver)
    login_page.delete_all_cookies()
    login_page.go_to()
    login_page.wait_for_page_loaded()
    login_page.set_credentials(username=username, password=password)
    login_page.click_login_button()
    if login_page.is_first_login():
        login_page.first_user_setup()
    all_updates_page = AllUpdates(webdriver)
    all_updates_page.wait_for_page_loaded()


def app_login_page(webdriver, datasets):
    @print_timing("selenium_app_specific_user_login")
    def measure():
        app_specific_user_login(webdriver, username='admin', password='admin')
    measure()


def view_config_page(webdriver, datasets):
    page = BasePage(webdriver)
    app_specific_user_login(webdriver, username='admin', password='admin')

    @print_timing("selenium_approvals_view_config_page")
    def measure():
        page.go_to_url(f"{CONFLUENCE_SETTINGS.server_url}/plugins/servlet/approvalmacro/system/configuration")
        page.wait_until_visible((By.CLASS_NAME, "admin-heading"))
        # Check whether form has been rendered on page by checking headings
        page.wait_until_visible((By.XPATH, "//h3[text()='General']"))
        page.wait_until_visible((By.XPATH, "//h3[text()='Notifications']"))
        page.wait_until_visible((By.XPATH, "//h3[text()='Permissions']"))
        page.wait_until_visible((By.XPATH, "//h3[text()='Terminology']"))

    measure()


def view_search_page(webdriver, datasets):
    page = BasePage(webdriver)

    @print_timing("selenium_approvals_view_search_page")
    def measure():
        page.go_to_url(f"{CONFLUENCE_SETTINGS.server_url}/plugins/servlet/approvalmacro/main")
        # check my approvals tab has rendered
        page.wait_until_visible((By.XPATH, "//div[text()='My Approvals']"))
        # check statistics tab has rendered
        page.wait_until_visible((By.XPATH, "//div[text()='Statistics']"))

    measure()


def view_space_settings(webdriver, datasets):
    page = BasePage(webdriver)

    @print_timing("selenium_approvals_view_space_settings")
    def measure():
        space_key = random.choice(SPACE_KEYS)
        page.go_to_url(f"{CONFLUENCE_SETTINGS.server_url}/plugins/approvalmacro/space/configure.action?key={space_key}")

        # Check settings container has rendered
        page.wait_until_visible((By.CLASS_NAME, "ac-approval-container"))
        # Check whether form has been rendered on page by checking headings
        page.wait_until_visible((By.XPATH, "//h3[text()='Configuration']"))
        page.wait_until_visible((By.XPATH, "//h3[text()='Permissions']"))
        page.wait_until_visible((By.XPATH, "//h3[text()='Teams']"))

    measure()
